[project]
name = "simplempi"
version = "0.1.1"
dependencies = [
    "mpi4py",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "sphinx",
    "sphinx_rtd_theme",
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 80
target-version = ['py37']
